version: '3'
services:
  luya_composer:
    image: composer
    volumes:
      - ./:/app
    command: composer install --ignore-platform-reqs 
  luya_db:
    image: mysql:5.7
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: luya
      MYSQL_DATABASE: luya_kickstarter
      MYSQL_USER: luya
      MYSQL_PASSWORD: luya    
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - "43306:3306"
  luya_web:
    # image: trafex/php-nginx
    build:
        dockerfile: docker/Dockerfile
        context: ./
        target: luya_web
    volumes:
      - ./:/app
      - ./logs/error.log:/dev/stderr
      - ./logs/access.log:/dev/stdout
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./bin/luya.sh:/usr/local/bin/luya
      - ./bin/setup.sh:/usr/local/bin/setup
    ports:
      - "8080:80"
    restart: unless-stopped
volumes:
  mysql-volume:
